### ISSUE TITLE
fyi: NPM Issue causes conflicting `peerDependency` with `tree-sitter-swift`.

### ISSUE THREAD

**Issue by moshe-foreflight** [amaanq/tree-sitter-objc#19]
### Did you check existing issues?

- [x] I have read all the [tree-sitter docs](https://tree-sitter.github.io/tree-sitter/using-parsers) if it relates to using the parser
- [x] I have searched the existing issues

### Tree-Sitter CLI Version, if relevant (output of `tree-sitter --version`)

tree-sitter 0.24.5

### Describe the bug

Installation alongside `tree-sitter-swift` fails, reporting a conflicting `peerDependency` version for the `tree-sitter` dependency.  

This is likely due to [this bug in `npm`](https://github.com/npm/cli/issues/3666). Reporting here because I've been able to work around this issue by installing `tree-sitter-cli`. (No idea why this works.)

### Steps To Reproduce/Bad Parse Tree

1. `npm install tree-sitter-swift`
2. `npm install tree-sitter-objc`

### Expected Behavior/Parse Tree

Installation of the package should succeed.

### Repro

```
brew install node;
mkdir tree-sitter-repro && cd tree-sitter-repro;
npm init -y;
npm i tree-sitter-swift;
npm i tree-sitter-objc;
```

This will fail.

If we run `npm i tree-sitter-cli` and try again, then `npm i tree-sitter-objc` succeeds.

**Comment by amaanq** [comment]
tell swift to upgrade

**Comment by moshe-foreflight** [comment]
Yep, already did. 

https://github.com/alex-pinkus/tree-sitter-swift/issues/461#issuecomment-2566835272

There's got to be a better way to keep these NPM packages in sync, no?
