### ISSUE TITLE
Support for nullable type specifier

### ISSUE THREAD

**Issue by theHamsta** [amaanq/tree-sitter-objc#8]
Hi! Thank you for maintaining this fork!

I tried it out on a random Objective-C file (https://github.com/theHamsta/HandBrake/blob/c50a83650cb9aff313a404e2372c2b3a206ae420/macosx/HBQueue.m#L869-L879) and found that this grammar doesn't seem to `nullable` in Objective C. I don't know whether `nullable` is an allowed part of the grammar. Disclaimer: I've no idea about Objective-C and what is legal grammar in this language.

https://stackoverflow.com/questions/32452889/difference-between-nullable-nullable-and-nullable-in-objective-c

**Comment by amaanq** [comment]
It stemmed from the pragma calls causing an error (adding preproc_call to interface/implementation blocks increased the state count by 900...), I've added it anyways for better highlighting support and added handbrake as a test suite, that's nice to have!

Next CI update of nvim-ts should have it fixed now :grin:

**Comment by theHamsta** [comment]
> It stemmed from the pragma calls causing an error (adding preproc_call to interface/implementation blocks increased the state count by 900...), I've added it anyways for better highlighting support and added handbrake as a test suite, that's nice to have!
> 
> Next CI update of nvim-ts should have it fixed now grin

As I said, no idea what is legal to do in objc. I never used it and only glanced over random source files. Thank you for considering the source files!

**Comment by amaanq** [comment]
It's legal to do so...but objc is a nightmare :laughing: minimizing state count was just near impossible w/ this one
